name: pettie_petstore
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: ^4.6.5
  google_fonts: ^4.0.3
  flutter_otp_text_field: ^1.1.1
  font_awesome_flutter: ^10.4.0
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  line_awesome_flutter: ^2.0.0
  cloud_firestore: ^4.5.3
  carousel_slider: ^4.2.1
  equatable: ^2.0.5

 
 
  

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/on_boarding_screen/

   


