// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWauFwT1-nWAyq7my3kzdR0e2VngpMC1Y',
    appId: '1:513171884416:web:9513801d3cf7315ee35965',
    messagingSenderId: '513171884416',
    projectId: 'flutter-pettie',
    authDomain: 'flutter-pettie.firebaseapp.com',
    storageBucket: 'flutter-pettie.appspot.com',
    measurementId: 'G-T4WC72LTLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJnLeUJjAmb3u5k2VkwLis-RpHCeeTUqY',
    appId: '1:513171884416:android:a9f40710c0116f91e35965',
    messagingSenderId: '513171884416',
    projectId: 'flutter-pettie',
    storageBucket: 'flutter-pettie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEolp1PiQgMuq_byrV29vDg7e8fVWZ490',
    appId: '1:513171884416:ios:7285d938e9c87069e35965',
    messagingSenderId: '513171884416',
    projectId: 'flutter-pettie',
    storageBucket: 'flutter-pettie.appspot.com',
    androidClientId: '513171884416-g6h4v89itc9ir9bq7lg91oa915mlm09v.apps.googleusercontent.com',
    iosClientId: '513171884416-t21uaga4nbrae5dib1pk00eqdeo0tdup.apps.googleusercontent.com',
    iosBundleId: 'com.example.pettiePetstore',
  );
}
